### ISSUE TITLE
html标签用过哪些？块元素特点？

### ISSUE THREAD

**Issue by honxinn** [honxinn/web-blog#6]
# html标签用过哪些？块元素特点？

    style、script、div、h1-5、p、span、strong、img、a、ul、li、dt、tt、i、b、em

> 块元素的特点是它可以更改元素高宽、独占一行。

> 行内元素只允许更改内外边距，无法更改高度宽度，且行内元素只占自己自身内容区域，不会独占一行

常用的块元素有`div`、`h1-5`、`p`，行内元素有`span`、`b`、`i`、`tt`、`em`

但是在实际的项目中，只用块元素和行内元素是无法满足需求的，这时候就需要用到行内块元素去满足一行可以所占多个标签

> display: block | inline | inline-block
> block: 块元素，独占一行，可以设置高度宽度
> inline: 行内元素，只占自身内容区域，不能设置高度宽度
> inline-block: 行内块元素，可以设置高度宽度且在页面中只占内容区域宽度

## 让我们来看一个例子
html部分
```html
 <div class="block">块元素</div>
    <span class="inline">行内元素</span>
    <div class="inline-block">行内块元素</div>
```
css部分
```css
.block {
    border: 1px solid blue;
}

.inline {
    width: 300px;
    border: 1px solid red;
}

.inline-block {
    width: 300px;
    display: inline-block;
    border: 1px solid green;
}
```
我们现在来看看页面中的效果
### 整个页面

![image](https://user-images.githubusercontent.com/49867035/132706377-b4617a63-f835-4198-8a83-2caac0d26c4f.png)

### 块元素所占区域

![image](https://user-images.githubusercontent.com/49867035/132706420-8b3f3038-01e7-49ae-a7a1-dec89bb271f3.png)

### 行内元素所占区域

![image](https://user-images.githubusercontent.com/49867035/132706467-b12e56bb-f559-4b51-b410-60a16acf1406.png)

### 行内块元素所占区域

![image](https://user-images.githubusercontent.com/49867035/132706494-492e4ee8-90fd-4a7e-8465-f53dc1f5bc63.png)

# 结论
从上面四幅图我们可以看出，第一个div为块元素并且它占了整个页面的一行；而第二个span标签为行内元素，它只占了内容区域的一部分；第三个div原本是块元素，我们在css中将它设置成了行内块元素并且给它和第二个span标签设置了指定宽度，效果是行内元素并没有因为设置了宽度而变化，但是行内块元素明显的可以看到改变了宽度并且与行内元素同行，不会独占一行。
